### PR TITLE
Playlists Browser: enable searching of contents

### LINKED ISSUE #1588: Add search to Playlist Browser
I would like to search in playlists without switching the browser.

### PR DESCRIPTION
**Pull request by declension**
@lazka - as discussed really. Please have a look, we can either then merge or update first.

 * Add searchbar as per other browsers, mostly.
 * Query is normal QL syntax
 * Searches persist across playlists selection
 * Text-compatible filtering supported too (TODO: ~playlists tag should select playlist)

Closes #1588.

### CODE REVIEW

**Comment by declension** [comment]
@lazka - Thanks. 

Weird, I can't replicate that UI behaviour; the queue stays shut for me, and if I don't show the songpane, I don't get a songpane at all it seems. 

As for the `active_filter()`... I see. Is it in fact possible to _remove_ it here entirely, as newly added songs will never be auto-added to a playlist (well, not without a whole lot new work)? That said, songs removed from the library should get removed from the songlist I guess, and it seems safer to implement it as a filter on both active playlist and text filter... so maybe I'll do that.

**Comment by lazka** [comment]
I mean if you hide the queue completely, not just close the expander.

for ``active_filter()``, removals are still handled in the song list directly atm, so you can probably just remove it for now.

**Comment by declension** [comment]
Oh, right, I forgot you could even _do_ that (again...)! 

I've fixed that behaviour in the packing (AFAICT), and as for the `active_filter`, made it consistent with the others for now.

Perhaps we can think about cleaning that interface up at some point? IMO it feels a bit inconsistent with the rest of the Browser interface, or something.

**Comment by declension** [comment]
@lazka - are you happy for me to merge the updated version?

**Pull request merged**
