### PR TITLE
Option for multiple queries in Search Browser

### PR DESCRIPTION
**Pull request by blimmo**
This is a prototype for ~~a new browser, similar to the Search browser, that creates a query by &ing together subqueries.~~ an option on the search browser to allow multiple queries to be entered, with the overall query generated by &ing together the subqueries.

The idea is that the user can leave some subqueries alone (say `#(rating >= 0.5)`) while changing another (say `genre = classical`). I think it could also help people unfamiliar with the ql query language use the search browser especially if using saved searches.

Possibly addresses #809 but that issue is rather broad.

Example:
image

Todo:
- [x] Separator between queries
- [x] Save queries on close
- [x] ~~Automatically add queries when chosen from combobox dropdown~~ Add button

Possible future changes
- Clear button (on right click?)
- Display names for saved searches added
- Negation button?
- Edit queries?

### CODE REVIEW

**Comment by blimmo** [comment]
I've got stuck with the third item in the todo list: detecting when a saved search has been clicked in order to automatically add it.

The `SearchBarBox` simply emits a `query-changed` signal whenever a valid query has been input and doesn't distinguish between typed ones and saved ones chosen.  
In fact digging a bit deeper it looks like `ComboBoxEntrySave` doesn't distinguish either.

Should I edit `ComboBoxEntrySave` to emit a new signal when a saved query is chosen?  
(also I can't find anything on how Gtk signals work: are they propagated to parent widgets like events?)

**Comment by blimmo** [comment]
On second thoughts adding queries automatically when chosen from the combobox is probably against the idea of comboboxes.  
Instead I've added a button to add chosen queries easily with the mouse.

I'd appreciate comments on the UX (I'm biased since I wrote it):
- Do I need some more explanation of what's going on to the user? I think it's pretty obvious except possibly that the queries are being &ed but I can't think of a good way to display that.
- I think the name could use some work.

**Comment by frestr** [comment]
This seems like a nice idea. We already have quite a few browsers though, and this is pretty similar to the search browser. Perhaps it could be added to the already existing search browser instead? It doesn't interfere with the old use case (single query) as far as I can see.

**Comment by frestr** [comment]
> Maybe it should be an option on the preferences button to enable multiple searches?

That could work too.

**Comment by blimmo** [comment]
Ok, I've attempted to move the functionality I had in my separate browser into a new version of `SearchBarBox`.

Unfortunately I obviously want the listbox underneath the `SearchBarBox`'s combobox so I've changed `SearchBarBox` to inherit from `Gtk.Grid` instead of `Gtk.HBox` which Gtk recommends over boxes apparently.

This promptly broke all the other browsers using `SearchBarBox.pack_start` so I implemented a replacement pack_start.

I think just having an HBox like before in a VBox with the listbox also in would be much easier but I can't think of a way to do that within the `SearchBarBox` object since it is itself the HBox I'd want to put in the VBox.

Anyway I also seem to have broken a whole bunch of other tests and I have no idea why. I'll look at them in more detail tomorrow.

**Comment by blimmo** [comment]
I've changed `SearchBarBox` back to inheriting from `Gtk.Box` and fixed the tests (apparently missing a config option from the default config breaks 221 tests :P).

To get the listbox underneath the rest of the search bar I'm packing the listbox into the actual `SearchBar` browser outside of the `SearchBarBox` which is obviously less than ideal (`MultiSearchBarBox` doesn't work unless the user does this).

**Comment by blimmo** [comment]
Ok, I'm quite happy with this now.

The beheaviour of the Search Browser is unchanged unless the user ticks a checkbox in the preferences button so this shouldn't be disruptive to existing users.

I think the other items I had on the todo can be added later; I might make another PR or two later.

The only thing I'm really concerned about is packing the `FlowBox` in `SearchBar` instead of `SearchBarBox` but I can't think of a solution to that.

Any comments or suggestions welcome.

**Comment by frestr** [comment]
Nice, it looks pretty good now.

Some feedback:

- The flowbox acts is a bit funky with multiple lines, as it tries to make the items in every "column" of the same length. This can be a bit annoying when later removing queries, as everything is reflowed. Not sure how to prevent this though.
- The "search after typing" option seems to be ignored in multiquery mode.
- Doing queries in non-multiquery mode adds queries to multiquery even though it is disabled. This can be seen by doing the following:
  1. Disable multiquery and "search after typing".
  2. Make a query and press enter to execute it. Repeat a few times.
  3. Turn on multiquery.
- A "clear queries" button when right-clicking the flowbox would've been nice (not very important though).

> The only thing I'm really concerned about is packing the FlowBox in SearchBar instead of SearchBarBox but I can't think of a solution to that.

It's not very clean, but I don't think it should be an issue.

**Comment by frestr** [comment]
> I guess it's mostly a problem when removing a few queries at once?

Yeah, it's not a big issue, so it's okay to leave it for later.

One last thing: it would probably be a good idea to disallow adding empty queries (which happens when pressing enter with no query text).

**Comment by blimmo** [comment]
Ah good point. Thanks again for your feedback!

**Comment by blimmo** [comment]
Yeah, there's nothing more I want to do atm so unless you can see any problems feel free to merge!

**Pull request merged**
