### PR TITLE
Added support for custom ellipsizing in filepath column

### PR DESCRIPTION
**Pull request by Meriipu**
The configuration feels a tiny bit unclean. 

Implements https://github.com/quodlibet/quodlibet/issues/2251

### CODE REVIEW

**Comment by Meriipu** [comment]
oh I think I messed up the direction of my merge

**Comment by Meriipu** [comment]
I can look into these when I have time (it might be a while). The suggested improvements all make sense.

**Comment by Meriipu** [comment]
so I tried with an enum.Enum at first but it turned out a bit too complex for me at least. 
Putting the dict (pretend-enum) of modes in config.py does not seem like the wisest decision, as it requires importing pango and stuff.

is defining the text version ("MIDDLE", hardcoded) in config.py a problem?
the example lines seem tricky/too specific to me to include differently. 

other than that there should be fewer magic constants floating around now...

**Comment by Meriipu** [comment]
I ran into a KeyError when trying to run the last commit with a config file based on the earlier commit (that used numbers rather than the string versions). 

I do not think that is something that will occur if the value was set for the first time to be one of the string ones but I suppose it might not hurt to check

Perhaps this is also a bit too niche so that it might be better to just close it unless somebody else really hates the default ellipsizing behaviour of middle. Applying this patch personally for my own use to my builds works fine for me either way.

**Comment by declension** [comment]
Cleaning up old PRs 

> Perhaps this is also a bit too niche so that it might be better to just close it unless somebody else really hates the default ellipsizing behaviour of middle. Applying this patch personally for my own use to my builds works fine for me either way.

Thanks, will close for now then.

**Pull request closed without merging**
