### PR TITLE
Update Polish translation for 4.1

### PR DESCRIPTION
**Pull request by piotrdrag**
Please also cherry-pick to master.

### CODE REVIEW

**Comment by lazka** [comment]
```
/home/user/app/quodlibet/po/pl.po:6031: a format specification for argument 'title', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
/home/user/app/quodlibet/po/pl.po:6081: number of format specifications in 'msgid_plural' and 'msgstr[0]' does not match
```

**Comment by piotrdrag** [comment]
These look correct in the translation:

```#: ../quodlibet/qltk/songsmenu.py:42
#, python-format
msgid "Remove track: \"%(title)s\" from library?"
msgid_plural "Remove %(count)d tracks from library?"
msgstr[0] "Usunąć ścieżkę „%(title)s” z kolekcji?"
msgstr[1] "Usunąć %(count)d ścieżki z kolekcji?"
msgstr[2] "Usunąć %(count)d ścieżek z kolekcji?"
```

```
#: ../quodlibet/qltk/songsmenu.py:422
#, python-format
msgid "_Show in File Manager"
msgid_plural "_Show %d Files in File Manager"
msgstr[0] "_Wyświetl w menedżerze plików"
msgstr[1] "_Wyświetl %d pliki w menedżerze plików"
msgstr[2] "_Wyświetl %d plików w menedżerze plików"
```

**Comment by lazka** [comment]
hm, weird, I'll have a look

**Comment by lazka** [comment]
I've pushed some (hopefully) fixes. Please try to rebase.

I'll add some tests so this doesn't happen again.

**Comment by lazka** [comment]
I've added a test in 275b31b642347

**Comment by lazka** [comment]
Thanks!

master: a1b9ab01b29ac

**Pull request merged**
