### PR TITLE
Add plugin for rich presence in Discord.

### PR DESCRIPTION
**Pull request by teeleafs**
Check-list
----------

 * [X] There is a linked issue discussing the motivations for this feature or bugfix: Add plugin for for rich presence in Discord #3423 
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [X] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------
This change is adding a plugin to publish the currently playing song information as a Discord status message using the pypresence library.

The song information fields to be displayed as a Discord status are user-configurable, and accept standard Quodlibet patterns.

The status information appears as follows, and due to Discord limitations, the status will show that a game is being played, and it is not feasible to display the album art.

image

### CODE REVIEW

**Comment by teeleafs** [comment]
Are these setup/known errors? I don't see anything related to my change.

**Comment by declension** [comment]
Thanks, looks promising

One thing we want here (I started writing a similar one a while ago but ran out of time) - in the `pyproject.toml` can you add
```toml
pypresence = {version = "^4.2.1", optional = true}

[tool.poetry.extras]
# Use with poetry install -E plugins
plugins = ["musicbrainzngs", "pyinotify", "dbus-python", "paho-mqtt", "soco", "pypresence"]
```

Also, have a look at some of the other plugins for how do to config with more helpers / safety e.g. animosd / waveformseek for one style (probably the best) or mqtt for `PluginConfigMixin` style

**Comment by teeleafs** [comment]
Will do, hopefully by this weekend!

**Comment by declension** [comment]
@teeleafs you'll need to do a `poetry lock --no-update` I think

**Comment by teeleafs** [comment]
> you'll need to do a poetry lock --no-update I think
Done!

**Comment by declension** [comment]
Thanks!

**Pull request merged**
