### PR TITLE
update french translation

### PR DESCRIPTION
**Pull request by brunob**
WIP refine #2240 ; i'll ping you when i'll think it could be merged ;)

### CODE REVIEW

**Comment by brunob** [comment]
@kellogsgit @spxxxk @pierremoreau i don't know if french is your native language, so i'll speak english here.

I was about to change "titre" to "morceau", since the term "titre" could make confusion in some case like this one : "song list" => "liste de titres" sounds strange and "liste de morceaux" seems better to me.

I've checked what term is used in rhythmbox, and sometimes it's "titre" another time it's "morceau", that's the beauty of french language ^^

Any thoughts about it ?

**Comment by spxxxk** [comment]
iTunes uses "morceaux", Google Play Music uses "Titres". Choose your side ! ;)
Oh, and I don't use the french locale, so I'll let others speak.

**Comment by ptitjes** [comment]
I don't use the french locale neither even if I'm native too...
However, I do agree using "morceau" sounds better !

**Comment by lazka** [comment]
Any action needed here?

**Comment by brunob** [comment]
@lazka not for now, thx for remminder, i'll ping you when i it will be ok ;)

**Comment by declension** [comment]
Any updates on this PR?

**Comment by brunob** [comment]
@declension no sorry, i'm a bit afk these times, sorry, i'll try to finish it asap.

**Comment by declension** [comment]
@brunob thanks & no worries - nothing urgent, just seeing what the status was.

**Comment by lazka** [comment]
Please open a new PR if anything changes here.

**Comment by brunob** [comment]
'k, & sorry for letting this one on idle...

**Pull request closed without merging**
