### PR TITLE
sort by date added in Album List Browser

### LINKED ISSUE #3399: Album browser: Sort by Date Added (or sort by any tag)
Untitled

The proposed change
-------------------
An option to sort albums by the date added in the album browser (and possibly others too).

(This would also be fixed by #821.)

Benefits of this change
-----------------------
Easily find the albums you recently added, without requiring a query with some arbitrary cutoff time period.

### PR DESCRIPTION
**Pull request by urielz**
Check-list
----------

  * [x] There is a linked issue discussing the motivations for this feature or bugfix
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [x] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------
adds the ability to sort by date added to the "Album List" browser. This was motivated by #3399

**Edit:** Closes #3399.

### CODE REVIEW

**Review by CreamyCookie — APPROVED** [review]
Looks good to me 

(Nothing to do with this PR, but there seems to be a lot of code duplication in that file.)

**Comment by CreamyCookie** [comment]
I guess this is small enough to be merged without additional review (and given how long this has been open..)

**Comment by CreamyCookie** [comment]
I guess this is small enough to be merged without additional review (and given how long this has been open..)

Thanks @urielz ! =)

**Comment by urielz** [comment]
> I guess this is small enough to be merged without additional review (and given how long this has been open..)
> 
> Thanks @urielz ! =)

Nice. Thanks for reviewing it! 👍

**Pull request merged**
