### PR TITLE
Depend on faulthandler

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by urielz** [comment]
@lazka I just pull the codebase to sync the new PRs with my local QL and I'm getting this error when I use the  _launcher script: 

Is the 3.8.1 bundle missing some dependencies now that this is merged?

/Applications/QuodLibet.app/Contents/MacOS/run ~/research/quodlibet/quodlibet/quodlibet.py

Traceback (most recent call last):
  File "./quodlibet/quodlibet.py", line 14, in <module>
    sys.exit(main())
  File "/Users/uriel/Downloads/quodlibet-master/quodlibet/quodlibet/main.py", line 36, in main
    quodlibet.init()
  File "/Users/uriel/Downloads/quodlibet-master/quodlibet/quodlibet/_init.py", line 57, in init
    _init_gtk_debug(no_excepthook=no_excepthook)
  File "/Users/uriel/Downloads/quodlibet-master/quodlibet/quodlibet/_init.py", line 30, in _init_gtk_debug
    from quodlibet.errorreport import enable_errorhook
  File "/Users/uriel/Downloads/quodlibet-master/quodlibet/quodlibet/errorreport/__init__.py", line 9, in <module>
    from .main import enable_errorhook, errorhook
  File "/Users/uriel/Downloads/quodlibet-master/quodlibet/quodlibet/errorreport/main.py", line 28, in <module>
    from .faulthandling import FaultHandlerCrash
  File "/Users/uriel/Downloads/quodlibet-master/quodlibet/quodlibet/errorreport/faulthandling.py", line 20, in <module>
    import faulthandler
ImportError: No module named faulthandler

**Comment by lazka** [comment]
> Is the 3.8.1 bundle missing some dependencies now that this is merged?

Yes. travis-ci uses https://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-latest.dmg which I update on packaging/dependency changes.

Sorry for the inconvenience.

**Comment by urielz** [comment]
Thanks for the help!

**Comment by ptitjes** [comment]
@lazka I have a "Error: nothing provides python2-faulthandler needed by exfalso-3.8.99-18.1.noarch" under Fedora 25 when installing unstable QL. Do you know how I can fix that ?

**Comment by lazka** [comment]
Oh, I assumed it was in fedora, but looks like it was just added recently. I'll have a look.

**Comment by lazka** [comment]
I've reverted this for now.

**Comment by pschwede** [comment]
For me (manjaro) including faulthandler worked out perfectly after I removed my manual installation of faulthandler via pip2.

**Comment by lazka** [comment]
faulthandler is in fedora 25 since yesterday. But I noticed that dnf caches the package list and that cache seems to expire every 48 hours, so in a few days this can be re-reverted I think.

**Comment by lazka** [comment]
@ptitjes  can you try `sudo dnf install python2-faulthandler` now?

**Comment by ptitjes** [comment]
@lazka Yes, it pulls python2-faulthandler 2.4-1.fc25 from the updates repository.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
