### PR TITLE
Closes #3631: Remove Web Lyrics plugin

### LINKED ISSUE #3631: Remove Web Lyrics plugin
The proposed change
-------------------
Remove the Web Lyrics plugin, as its main functionality has been broken for a while and it only "works" on Linux right now. The only thing that does work on Linux is the alternative search function. I address that feature in the "Any issues this might cause" section.

Accessing `https://lyrics.wikia.com/api.php?client=QuodLibet&action=lyrics&func=getSong&artist=Sia&song=Together&fmt=xml` only returns:

> You're not authorized to access this API. For information about Wikia API licensing please contact support@wikia-inc.com.pirat@anon-PC:/tmp

Accessing `https://lyrics.wikia.com` redirects to `https://lyrics.fandom.com/wiki/Main_Page`, which shows a message:

> This wiki has been disabled

As mentioned in #2558, the scrolling to lyrics section also stopped working at some point.

Benefits of this change
-----------------------
* Cleaner code base
* Less to maintain
* Buggy plugins might make Quod Libet look less maintained than it is

If the plugin would be removed, we can close #2539 : macOS: lyricswindow plugin not available.

I think if we found a good API and someone wanting to implement it, it would also be better to add it to the viewlyrics plugin. If lyrics couldn't be found in tags or a file, they could be loaded from that API.

Any issues this might cause
---------------------------
Some users might not be happy about it being removed, if they still used it for the alternative search function (search at configurable url for `lyrics {artist} {title}`). 

However, it seems unlikely to me that many people use that, and even then we still have the "Website Search" plugin, where you can do the same (though manually).

----

See also https://github.com/quodlibet/quodlibet/issues/3444#issuecomment-701203619, which mentions some alternative proposals (but also removing the plugin).  

Of course, if nobody is interested in working on an alternative (which seems to be the case), we can always remove the plugin first, as, of course, the deleted [plugin code](https://github.com/quodlibet/quodlibet/blob/8b58a81b077e00b32cc4ad30520ccc8ca70f4406/quodlibet/ext/events/weblyrics.py) can always be reused.

### PR DESCRIPTION
**Pull request by CreamyCookie**
Check-list
----------

 * [x] There is a linked issue discussing the motivations for this feature or bugfix
 * [x] Unit tests have been added where possible
 * [x] I've added / updated documentation for any user-facing features.
 * [x] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------
Closes #3631 which contains the explanation for this.

### CODE REVIEW

**Comment by CreamyCookie** [comment]
@declension Not sure why it failed here. Log shows:

```
2021-04-18T19:53:13.3378703Z =================================== FAILURES ===================================
2021-04-18T19:53:13.3380508Z __________________________ Tcopool.test_pause_resume ___________________________
2021-04-18T19:53:13.3382325Z 
2021-04-18T19:53:13.3384152Z self = <tests.test_util_copool.Tcopool testMethod=test_pause_resume>
2021-04-18T19:53:13.3385847Z 
2021-04-18T19:53:13.3387393Z     def test_pause_resume(self):
2021-04-18T19:53:13.3389305Z         copool.add(self.__set_buffer)
2021-04-18T19:53:13.3391033Z >       self._assert_eventually(True)
2021-04-18T19:53:13.3392513Z 
2021-04-18T19:53:13.3394082Z tests/test_util_copool.py:56: 
2021-04-18T19:53:13.3395737Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2021-04-18T19:53:13.3398116Z 
2021-04-18T19:53:13.3400967Z self = <tests.test_util_copool.Tcopool testMethod=test_pause_resume>
2021-04-18T19:53:13.3403691Z value = True
2021-04-18T19:53:13.3406239Z 
2021-04-18T19:53:13.3408952Z     def _assert_eventually(self, value):
2021-04-18T19:53:13.3411510Z         for i in range(100):
2021-04-18T19:53:13.3414011Z             Gtk.main_iteration_do(False)
2021-04-18T19:53:13.3416590Z             if self.buffer is value:
2021-04-18T19:53:13.3419230Z                 return
2021-04-18T19:53:13.3421740Z >       assert self.buffer is value
2021-04-18T19:53:13.3424367Z E       AssertionError: assert None is True
2021-04-18T19:53:13.3427315Z E        +  where None = <tests.test_util_copool.Tcopool testMethod=test_pause_resume>.buffer
2021-04-18T19:53:13.3429573Z 
2021-04-18T19:53:13.3431264Z tests/test_util_copool.py:33: AssertionError
```

**Comment by declension** [comment]
> @declension Not sure why it failed here. Log shows:

I hate that test, it's super flakey on some setups

**Comment by CreamyCookie** [comment]
> I hate that test, it's super flakey on some setups

Ah.. that's why I feel like I had seen this before.

**Comment by declension** [comment]
Thanks!

**Pull request merged**
