### PR TITLE
fix bug with relative file names in enqueue and enqueue-files

### PR DESCRIPTION
**Pull request by pfps**
Here are the changes to fix the bug with relative file names in the cli arguments enqueue and enqueue-files.  I've also figured out how to do some testing of the commands.

### CODE REVIEW

**Comment by pfps** [comment]
Grumble, grumble.

I tried to be nice and remove the temporary files, but that's not allowed in two check setups.

**Comment by pfps** [comment]
I'm not sure how to fix up the mac test.

**Comment by declension** [comment]
Cleaning up old PRs. Sorry about the long delays.

@pfps any chance this can be rebased /merged from master and any tests fixed? If not (ever) I'll close otherwise let's try to get it merged

**Comment by pfps** [comment]
I think you will have to do it.   I tried to clone my repository but something didn't work right and I don't even see my branches in it.

**Comment by declension** [comment]
Path conflicts fixed and imported to local branch with new PR, so closing this in favour of #3478.

Thanks!

**Pull request closed without merging**
