### PR TITLE
Independent cover size for Album List and Cover Grid browser

### PR DESCRIPTION
**Pull request by urielz**
This PR allows to have independent values for the covers displayed in the Album List and Cover Grid browsers. The default value for the Cover Grid is set to 96, however users can set their preferred sized via the Advanced Preferences plugin.

### CODE REVIEW

**Comment by declension** [comment]
BTW you realise there's a scale factor in the Covergrid browser (which is independent of the Album List browser, and relative to the underlying preferences for both)?

**Comment by urielz** [comment]
Is it really independent? It looks to me that it uses the cover size value of Album List browser multiplied by the scale factor...

**Comment by declension** [comment]
Sorry @urielz, forgot to reply. Yes it's accessible via the covergrid prefs UI - click the cog in the right of the search bar in the browser and it's one of the settings there...

**Comment by urielz** [comment]
@declension thanks. missed that! 

It's completely unintuitive that the cover grid size for Cover Grid Browser is accessible via that menu and the cover grid size for Album List Browser is hidden in a plug-in menu in advanced preferences. 

I might give it a go and a slider for Album List cover size just like in Cover Grid. Unless there's a reason it's hidden in advanced preferences... ?

**Comment by declension** [comment]
> It's completely unintuitive that the cover grid size for Cover Grid Browser is accessible via that menu and the cover grid size for Album List Browser is hidden in a plug-in menu in advanced preferences.

Agreed. I only noticed it randomly at some point...

> I might give it a go and a slider for Album List cover size just like in Cover Grid. Unless there's a reason it's hidden in advanced preferences... ?

Yep, I definitely think this isn't an _advanced_ preference but belongs with the browser. For consistency if nothing else! Thanks :+1:

**Comment by urielz** [comment]
Thanks! Will close this now.

**Pull request closed without merging**
