### PR TITLE
Move to libsoup3

### LINKED ISSUE #4291: Move to libsoup3
The proposed change
-------------------
We use & package / require [libsoup](https://gitlab.gnome.org/GNOME/libsoup/) 3.x, not the 2.x we currently explicitly require

Benefits of this change
-----------------------
* v2 has been deprecated
* There are increasing difficulties, it seems, due to Gnome 42 (?) also moving
* It might actually be better, or whatever

Any issues this might cause
---------------------------
 * Lots, but see [libsoup 2 ->3 migration guide](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html)

### PR DESCRIPTION
**Pull request by declension**
* Actually require `3.0` via GI
* A few changes needed as per [porting guide](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html)
* Lots of CI / Docker changes
* A few docs updates

Closes #4291

### CODE REVIEW

**Comment by declension** [comment]
Thanks @lazka - I actually had a near-identical commit to f3636518a6ae5eac6c4c6436e85f3881418fe446 unpushed (but used the `GInputStream` body version instead)

**Review by lazka — APPROVED** [review]
hard to say as there isn't much coverage for all this, but lgtm (?)

**Comment by lazka** [comment]
(I'm fine with bumping min Python, also on macOS, but I wanted to wait for this so I can run the tests)

**Comment by declension** [comment]
> I'm fine with bumping min Python, also on macOS

Not sure I'm following - why the Python bump? 

> but I wanted to wait for this so I can run the tests. 

The cover / soup tests I just added here?

> Now that you merged in main I could try if wanted though, but not sure when.

Cool, let me know if I can help

**Comment by lazka** [comment]
> > I'm fine with bumping min Python, also on macOS
> 
> Not sure I'm following - why the Python bump?

because you pushed code requiring newer Python before.

> > but I wanted to wait for this so I can run the tests.
> 
> The cover / soup tests I just added here?

no, I meant running normal tests on "main"

> > Now that you merged in main I could try if wanted though, but not sure when.
> 
> Cool, let me know if I can help

**Comment by declension** [comment]
> because you pushed code requiring newer Python before.

Ah the [`list[Any]`](https://github.com/quodlibet/quodlibet/pull/4294/commits/98f8f7b3628bd9d863e5e4aaf4f5155cd7c205d4#diff-95cc0dd2e25607ea26c278c6c341b7a78ed55912c8eef2c92475d7267cd36b52R55) thing you mean? I reverted that when I realised it's too new, so hopefully no need now.

**Comment by declension** [comment]
OK I'm out of ideas for the Flatpak test failures :confused: 
The macOS thing seems to be an OpenSSL issue... :confused:

**Comment by lazka** [comment]
hm, test_https is passing on macOS though

**Comment by declension** [comment]
> hm, test_https is passing on macOS though. In theory that should cover all cases

ah good point. Even more confused now :flushed: 
What I saw though was this error:

```
 	W: [0183.549] HTTPRequest._sent: Failed sending GET request to https://ws.audioscrobbler.com/2.0?method=album.getinfo&api_key=107db6fd4c1c7f53b1526fafddab2c82&format=json&artist=The%20Beatles&album=Let%20It%20Be&mbid= (soup-session-error-quark: Could not parse HTTP response (0))
F
ERROR: failed tests/plugin/test_covers.py::test_live_cover_download[discogs-cover]:
	W: [0263.916] HTTPRequest._sent: Failed sending GET request to https://api.discogs.com/database/search?key=aWfZGjHQvkMcreUECGAp&secret=VlORkklpdvAwJMwxUjNNSgqicjuizJAl&format=CD&per_page=5&type=release&artist=The%20Beatles&release_title=Let%20It%20Be (soup-session-error-quark: Could not parse HTTP response (0))
```

with this on stderr (see [5016323447 logs](https://github.com/quodlibet/quodlibet/actions/runs/5016323447/jobs/8993054350?pr=4294#step:4:259)):

```
----------------------------- Captured stderr call -----------------------------
GLib-Net-Message: 17:04:23.671: end_openssl_io client: 5, 0, 0
GLib-Net-Message: 17:04:23.671: end_openssl_io client: 5, 0, 0

(setup.py:2523): GLib-GIO-WARNING **: 17:04:23.811: ../../../../jhbuild_checkoutroot/glib-2.74.7/gio/gtlsconnection.c:429: invalid property id 12 for "protocol-version" of type 'GParamEnum' in 'GTlsClientConnectionOpenssl'

(setup.py:2523): GLib-GIO-WARNING **: 17:04:23.811: ../../../../jhbuild_checkoutroot/glib-2.74.7/gio/gtlsconnection.c:429: invalid property id 13 for "ciphersuite-name" of type 'GParamString' in 'GTlsClientConnectionOpenssl'

(setup.py:2523): GLib-GIO-WARNING **: 17:04:23.837: ../../../../jhbuild_checkoutroot/glib-2.74.7/gio/gtlsconnection.c:429: invalid property id 12 for "protocol-version" of type 'GParamEnum' in 'GTlsClientConnectionOpenssl'

(setup.py:2523): GLib-GIO-WARNING **: 17:04:23.837: ../../../../jhbuild_checkoutroot/glib-2.74.7/gio/gtlsconnection.c:429: invalid property id 13 for "ciphersuite-name" of type 'GParamString' in 'GTlsClientConnectionOpenssl'
```
Making me think it's outdated cypher suites or something? IDK

**Comment by lazka** [comment]
hm, ok, I 'll try to build a new bundle with more update dependencies

**Comment by lazka** [comment]
skipped one test, but green

**Comment by lazka** [comment]
sure

**Pull request merged**
