### PR TITLE
Update Hebrew Translation (Master)

### PR DESCRIPTION
**Pull request by avma**
[https://gist.github.com/avma/7e32691c190441a20fe99ea6a5f5ce64](url)

### CODE REVIEW

**Comment by lazka** [comment]
What are you trying to do here? :)

**Comment by avma** [comment]
Well, I tried to push an update to the hebrew translation based on the master repository. (last time you asked me to creal a PL rather then an issue...)

**Comment by lazka** [comment]
OK, it looks like you are trying to merge the 4.2 branch on your fork into master here, and I don't see any commits from you as well.

If you want to update master then create a branch from master on your fork, commit there, and then open a PR against master here.

**Comment by avma** [comment]
Hope This time I did it right... ;) 
- forked master
- created an he.po file
- committed the file 
- created a pull request 

(it would be nice to have some more detailed instruction under the translation guidelines of how the process should  be carried out for the sake of other layman translators such as myself. currently the instruction says to create an issue...)

**Pull request closed without merging**
