### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by lazka** [comment]
Thanks.

Random translation related question: If we'd switch to an online translation tool, which one would you prefer?

**Comment by Vistaus** [comment]
NP :)

I very much prefer Transifex.

**Comment by lazka** [comment]
Thanks!

**Comment by lazka** [comment]
we've had some problems with transifex, so we now switched to weblate instead: https://twitter.com/QuodLibetApp/status/1392536335785791488

**Pull request merged**
