### PR TITLE
undo covergrid hacks

### PR DESCRIPTION
**Pull request by darthoctopus**
this is *considerably* faster for me (tested on Fedora 26).

### CODE REVIEW

**Comment by lazka** [comment]
Not the case here, about twice as slow. hmm..

**Comment by darthoctopus** [comment]
I should be more specific: I believe you are referring to performance on resize, and that does appear to be the case. however (at least for me) this also causes scrolling to be heavily CPU-bound (100% CPU utilisation for about half a minute whenever viewport is moved, vs 60 fps scrolling without the hack). I suspect but cannot prove that something is preventing hardware acceleration when these methods are overwritten.

**Comment by lazka** [comment]
I can't reproduce. Any change with the commit 84d95f92a2f on master? That should improve scrolling when covers get loaded.

**Comment by darthoctopus** [comment]
no change to scrolling performance, unfortunately.

It seems that commenting out the redefinition of `do_get_preferred_height_for_width` is sufficient to almost entirely get usable scrolling behaviour back.

**Comment by lazka** [comment]
ok, thanks, I'll have another look.

**Comment by declension** [comment]
Any updates on this PR?

**Comment by darthoctopus** [comment]
update: performance issues seem gone with current git master; must have been a graphics driver or GTK issue.

**Comment by lazka** [comment]
Thanks for testing again

**Comment by declension** [comment]
Closing old / broken PRs - please re-open or resubmit based on current `master` if this is still relevant. Thanks!

**Pull request closed without merging**
