### PR TITLE
operon: multiple file edit

### PR DESCRIPTION
**Pull request by remvee**
Check-list
----------

 * [X] There is a linked issue discussing the motivations for this feature or bugfix (see  #3417)
 * [x] Unit tests have been added where possible
 * [X] I've added / updated documentation for any user-facing features.
 * [X] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------

Allow editing multiple songs in a single text file with the operon edit command.  Please note: this change has a significant impact on the format of the text file to be edited!

The file is split into sections stating with a "File: .." line, indicating which file is being edited.  All key/value pairs following are interpreted as tags and their values for that file.  These pairs are indented to improve readability.

An example:

```
File: '/Music/Schostakowitsch/String-Quartet-7/01.Allegretto.flac'

  title=Allegretto
  composer=Dimitri Schostakowitsch
  album=String quartet Nr.7, op. 108
  genre=Classical
  tracknumber=1/3

File: '/Music/Schostakowitsch/String-Quartet-7/02.Lento.flac'

  title=Lento
  composer=Dimitri Schostakowitsch
  album=String quartet Nr.7, op. 108
  genre=Classical
  tracknumber=2/3

File: '/Music/Schostakowitsch/String-Quartet-7/03.Allegro.flac'

  title=Allegro
  composer=Dimitri Schostakowitsch
  album=String quartet Nr.7, op. 108
  genre=Classical
  tracknumber=3/3
```

### CODE REVIEW

**Comment by remvee** [comment]
I realize this would need some more test cases.  Please let me know if this change is at all close to what the [comment](https://github.com/quodlibet/quodlibet/pull/3418/files#diff-b5941404a9f3c4e61e19acc89b20df52L160) about editing files refers to.  If it is I'll add some tests for the multiple file aspect of this change.

**Comment by declension** [comment]
I'm not an Operon user. @lazka any thoughts?

**Comment by Phil305** [comment]
I use Operon heavily, this would be hugely beneficial for me.

@remvee, if you want, I'd be happy to help with writing some of those test cases, or testing manually on my machine (Fedora 33)

**Comment by remvee** [comment]
> I use Operon heavily, this would be hugely beneficial for me.
> 
> @remvee, if you want, I'd be happy to help with writing some of those test cases, or testing manually on my machine (Fedora 33)

If writing tests is what it takes to get this passed, I am happy to do it myself.  I've been using this version quite a lot for months now and it works really well for me.  @lazka ?

**Comment by declension** [comment]
@remvee picking this back up, yes I think some tests and a bit of documentation (user guide? inline help? Not sure) would be all we're missing now :+1:

**Comment by remvee** [comment]
> @remvee picking this back up, yes I think some tests and a bit of documentation (user guide? inline help? Not sure) would be all we're missing now +1

I've rebased to a more recent master commit and added some tests (enough?) but I am not sure on how to improve the documentation beyond what I've already committed in 4ce4da5.  Do you have some pointers?

**Comment by declension** [comment]
Apologies for dropping the ball on this one. I think it looks good to go now really.

@lazka any thoughts?

**Comment by declension** [comment]
OK, merging for now, and we'll see if it needs any tweaks.

**Comment by declension** [comment]
Thanks!

**Pull request merged**
