### PR TITLE
Added ModeBar

### PR DESCRIPTION
**Pull request by bernd-wechner**
My very first QL patch. Am getting my head around git, and github in the process and trying to set up up a workflow. 

Am very open to feedback. But also seriopusly appreciate accepting the request. Happy to modify it so it's optional if preferred, and take advice on how to make it optional. Or to look at internationalizing the label (could not see how to do that easily) or otherwise to make it fit the visions of look and feel I guess.

Real estate in this area is abundant on any normal sized screen and I found the two mode buttons cryptic at first and find their status hard to see (contrast between up and down images is low). So I added a very rough shod simple text statement as to the current mode. 

All feedback or improvement suggestions welcome. Am testing the ropes wit QL, PyDev and Git..

### CODE REVIEW

**Comment by lazka** [comment]
> My very first QL patch. Am getting my head around git, and github in the process and trying to set up up a workflow. 

:)

> Am very open to feedback. But also seriopusly appreciate accepting the request. Happy to modify it so it's optional if preferred, and take advice on how to make it optional. Or to look at internationalizing the label (could not see how to do that easily) or otherwise to make it fit the visions of look and feel I guess.

For translations you just have to wrap all translatable text with the magic `_` function e.g. `_("My text")`. But you have to keep in mind that translators will only see the text without context. So instead of `" and "` it would be better use something like `"%(repeat)s and %(shuffle)s"`, or just provide three fixed strings for all cases.

> Real estate in this area is abundant on any normal sized screen and I found the two mode buttons cryptic at first and find their status hard to see (contrast between up and down images is low). So I added a very rough shod simple text statement as to the current mode. 

Imo the two icons are a well established UI pattern by now and I'm not sure if adding a text label will make it easier/faster (besides for screen readers perhaps) to parse the state. Maybe someone else has an opinion to add here..

Not sure how easy that is to implement, but what about changing the color of the icons when they are active instead?

> All feedback or improvement suggestions welcome. Am testing the ropes wit QL, PyDev and Git..

**Comment by declension** [comment]
Thanks

+1 to what @lazka said really, i.e. once those i18n problems fixed there would be no _code_ problems, but... whilst I agree the current icons could be a bit clearer (or even larger), having pulled the PR, I don't see that _text_ here would be a UI improvement for users given the clutter it brings.

That said, these might make it more palatable to users:
 * Feature made optional via a prefs widget
 * Using the full name (_One Track_ / _Track Repeat_ etc) might be more useful
 * The text should probably be in parentheses i.e.  _(Weighted Shuffle, Repeat)_, hinting it's a translation of the button states to an extent.

There was a lot of discussion around on a big overhaul of play order (partially implemented now) in #1411, it's worth a look.

**Comment by bernd-wechner** [comment]
Thanks for the feedback so far. Very much appreciated (Am well into a rework of the library scanner on another local branch right now, more on that to come).

Am rearing to fix this one though as suggested. But some questions if you can spare a moment to handhold a rapidly upskilling newb:

@lazka 

1) What do you mean by `"%(repeat)s and %(shuffle)s"` ? 
I'd have though plurals and 'and' are all language specific so a conjunction like `" " + _("and") + " " ` seems appropriate.

2) WRT IMO a text feedback is pretty customary on other players and makes it readily visible. That said in my experience it's usually near the what's playing features, that show you the playing track etc, and it might be more at home there. For now was aiming at a MVP (minimum viable product) for a newb to offer up and get comment on.

@declension 

3) Sounds great and I like. I'll look at a prefs widget to propose as that's an area I want to upskill in. But if UI clutter is an issue, a config file setting with no UI is an option too. It is Quod Libet after all, Whatever You Like ... and that's one reason I've landed with it, namely a confidence that the community culture at least supports mainlining configurability to individual tastes and preferences.

4) Any tips on how to divine the current nuance of Repeat and Shuffle modes would please me, but I'll poke around too in the iterim. Reason I ask is the Repeat button I see (and I'm only using on browser, the File System one for now) simply toggles on/off doesn't have any nuancal options and Shuffle has only two `In Order` and `One Song` and I admit I find that wholly cryptic (i.e. I have no idea what it means). 

5) Rendering in parenthesis or not or fonts or location is all up for advice as I'm pretty unfussed. The UX desire is to see clearly with a glance at screen the current play mode I guess. That's what I'm angling for.

6) Will read #1411 later. A quick check now suggests much to digest and I'm not focussed enough right now.

7) As a total side observation `_` seems overloaded sadly, which surprised me for a language that doesn't support overloading ;-). But I'm getting warnings on unused variables on a list unpack from a function/generator return and so I reflexively replace that variable with `_`. Which is the custom and works fine. But if that is done in the class then the `_` can no longer be used for internationalization. Odd. At a  total guess for now I just named it dummy and I get no more unused variable warning (seems the semantics of that name are respected). Ah, am still learning python after a year or two of coding with it - but have never done internationalization before I guess)

**Comment by declension** [comment]
> 3) Sounds great and I like. I'll look at a prefs widget to propose as that's an area I want to upskill in. But if UI clutter is an issue, a config file setting with no UI is an option too.

Yes that's possibly better in cases like this - see the advanced preferences plugin for this purpose. However, as this discussion has prompted me to revisit #1411, including clarifying the confusing situation with the repeat button you mention. Note also that play-order plugins are exposed here, so it's not as simple as it first looks. I've got a few pending changes, so perhaps wait and see how they affect this before going any further.

In fact, the real solution for your aim here is a plugin (automatically and easily solving the prefs issue) once #152 is finally started, which I've also started thinking about now). Plugins are by far the most  useful, powerful and readily accepted development option especially for a first commit.  See the [plugin development documentation](https://quodlibet.readthedocs.io/en/latest/development/plugins.html). (note: in future, please file an issue here first before pull requests... and we do have over 400 open...)


> 7) As a total side observation _ seems overloaded sadly, which surprised me for a language that doesn't support overloading ;-). But I'm getting warnings on unused variables on a list unpack from a function/generator return and so I reflexively replace that variable with _. Which is the custom and works fine. But if that is done in the class then the _ can no longer be used for internationalization.

As a side reply: yes, it's pretty annoying. This is because `_` is `gettext` thus more of a C thing. See the [Python gettext docs](https://docs.python.org/2/library/gettext.html). Some people use `__` as the throwaway variable, though I usually like to give it a name of what it was anyway.

**Comment by lazka** [comment]
> 1) What do you mean by `"%(repeat)s and %(shuffle)s"` ? 
I'd have thought plurals and 'and' are all language specific so a conjunction like `" " + _("and") + " " ` seems appropriate.

See https://docs.python.org/2/library/stdtypes.html#string-formatting

No idea, my language skills are limited. If in doubt try to make it easier to translate I guess. You can have a look at the translation .po files to get a feeling for what translators see: https://github.com/quodlibet/quodlibet/tree/master/quodlibet/po

----

Regarding "_": master now imports those functions explicitly, so this should be less confusing.

----

Regarding this PR, still not convinced that this is an improvement, so closing.

**Pull request closed without merging**
