### PR TITLE
Unify cover art downloading

### LINKED ISSUE #2793: Default to higher quality images from Last.fm
We currently get the 300x300 images from Last.fm, but on investigation (as part of looking into #1279), larger resized, or even very large "original" images are often available...

### PR DESCRIPTION
**Pull request by declension**
New Cover Art plugin (see #1279)
 * Various API tweaks to cover art plugin, including new `ApiCoverSourcePlugin` to encapsulate this once
 * Update all existing cover plugins to support search
 * Tidy Discogs, and optionally allow secondary images
 * Improve lastfm search: use higher quality images where possible (Fixes #2793)
 * Allow HTTP 3xx to succeed, sometimes redirects are used
 * Add search to Cover Manager, and use new signals to communicate
 * Improvements to existing cover plugins
 * Use GTK Flowbox for faster rendering
 * Resize previews live by using native pixbuf scaling.
 * Saves original (though feature exists to resample and export as JPEG) - needs UI.

### CODE REVIEW

**Comment by declension** [comment]
Seems that Ubuntu 16.04 has GTK < 3.18, :disappointed: and yet [models with FlowBox need 3.18](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/FlowBox.html#Gtk.FlowBox.bind_model)

**Comment by lazka** [comment]
16.04 has 3.18.9

**Comment by declension** [comment]
> 16.04 has 3.18.9

OK thanks. Hmm, but that's weird then:
```
E       AttributeError: 'FlowBox' object has no attribute 'bind_model'
```
from [that 16.04 build](https://circleci.com/gh/quodlibet/quodlibet/3434).

**Comment by lazka** [comment]
Hm, right, confirmed in a VM. I guess something was fixed later: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816461

**Comment by declension** [comment]
Thanks. I guess I'll leave it with the older-compatible code for now. It does feel quite fast the FlowBox though

**Comment by lazka** [comment]
Nice work!

**Comment by declension** [comment]
Thanks @lazka :smile: ... took much longer than I was hoping but think it's good progress.

**Pull request merged**
