### PR TITLE
Update waveformseekbar.py

### PR DESCRIPTION
**Pull request by urielz**
User-friendly color picker for waveform
It uses class PluginConfigMixin pretty much in the same way the synchronized lyrics plugin does it

### CODE REVIEW

**Comment by declension** [comment]
Hmm, whilst I like(d) `PluginConfigMixin` (though am biased I guess), using _both_ systems seems bad, and switching between them doesn't seem related to this change.

Could you not just do it with the config proxies?

**Comment by urielz** [comment]
by _both_ you mean PluginConfigMixin and PluginConfig?

Thanks for the tips. I have zero experience with GTK and close to non with Python so this is mostly a learning experience for me. Might take a while to get it right :)

**Comment by declension** [comment]
> by both you mean PluginConfigMixin and PluginConfig?

Yes, there are I think *four* ways used of "doing config" in plugins. These two are probably the most common and take different approaches. The proxy method (`PluginConfig`) is newer and a bit more abstracted... there's discussion on #1827.

> Thanks for the tips. I have zero experience with GTK and close to non with Python so this is mostly a learning experience for me. Might take a while to get it right :)

No worries. Yes, probably will, but that's fine. Python should be fine but I find GTK+ (in Python) can be a near-undocumented black hole of time once you stray off the well-trodden paths. Luckily @lazka is around :smile:  (read [his excellent GTK+ 3 guide](https://python-gtk-3-tutorial.readthedocs.io/en/latest/) actually).

The most important aspect you already know - _QL is far, far more clever than it first seems_.

**Comment by urielz** [comment]
Excellent. I understand now. Thanks for pointing me in the right direction! I'll give it a try whenever I find some more free time.

**Comment by lazka** [comment]
> read his excellent GTK+ 3 guide actually

(I only worked on the API docs, not the gtk tutorial)

**Comment by lazka** [comment]
With the newest osx bundle it's now possible to run "setup.py quality". See #2117

**Comment by knockoutMice** [comment]
Could we also modify it so the slider doesn't jump, but _slides_? I haven't looked into the issue, but it deeply frustrates me. :)

If nobody jumps in, I'm gonna do it tomorrow if I don't need to modify the behavior of the original seekbar.

**Comment by urielz** [comment]
@knockoutMice too busy at the moment to fiddle with this. feel free to jump in. thanks!

**Comment by knockoutMice** [comment]
#2138

**Comment by declension** [comment]
Should we close this PR now in favour of #2138?

**Comment by urielz** [comment]
@declension yes, fine by me. I'm working on something else atm. I'll open another one if I comeback to this.

**Pull request closed without merging**
