### PR TITLE
Made tag scan multithreaded.

### PR DESCRIPTION
**Pull request by ewtoombs**
This was done to reduce the latency effects of network filesystems. I have
observed about a 3x speedup in the scan rate. That's over wifi. If I was
scanning over a wide area network, I would expect the speedup to be many times
that.

Check-list
----------

 * [ ] There is a linked issue discussing the motivations for this feature or bugfix
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [ ] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------

### CODE REVIEW

**Comment by lazka** [comment]
This assumes that MusicFile() is thread-safe, which it isn't. I think it calls into logging and config (any more?), so both of those need to be checked/marked for thread safety first.

**Comment by ewtoombs** [comment]
> This assumes that MusicFile() is thread-safe, which it isn't. I think it calls into logging and config (any more?), so both of those need to be checked/marked for thread safety first.

It isn't? It seemed to work OK when I tried it. I knew it reads some globals, but ... oh wait. Oh, no, if somebody *else* modifies the config, MusicFile()'s read could break. God damn it.

Well, I don't know enough about the code base to be able to answer this question of thread safety, then.

**Comment by lazka** [comment]
yeah, Python is very forgiving in that area because of the GIL, und config changes are rare.

**Comment by CreamyCookie** [comment]
@ewtoombs Thanks for the PR. I think this would be a cool addition (if MusicFile is made thread safe).

**Comment by declension** [comment]
OK, unmergeable for now then I guess. Re-open / repush if thread-safe fixes are found.

**Pull request closed without merging**
