### PR TITLE
add more zh_CN message translations

### PR DESCRIPTION
**Pull request by caiknife**
Check-list
----------

 * [x] There is a linked issue discussing the motivations for this feature or bugfix
 * [x] Unit tests have been added where possible
 * [x] I've added / updated documentation for any user-facing features.
 * [x] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------

### CODE REVIEW

**Comment by CreamyCookie** [comment]
@caiknife From what I can see the test failures are not caused by your commits.

**Comment by caiknife** [comment]
> 
> 
> @caiknife From what I can see the test failures are not caused by your commits.

OK. But could this PR be merged while not all the checks are successful?

By the way, I'm a software enginneer, guitar player, swing dancer from China. I like Quod Libet very much and have been managing my all music albums with Quod Libet for a long time.

I'd like to make a little effort for the i18n of Quod Libet. I will keep on working it.

**Comment by declension** [comment]
`master` should be fixed now - sorry about that.

> I'd like to make a little effort for the i18n of Quod Libet. I will keep on working it.
Thank you! This is helpful, and remind us to add you to the list of translators.

**Comment by CreamyCookie** [comment]
@caiknife 

> By the way, I'm a software enginneer, guitar player, swing dancer from China. I like Quod Libet very much and have been managing my all music albums with Quod Libet for a long time.

Very cool! Thank you, from me as well, for the additions and improvements. :+1:

**Pull request merged**
