### PR TITLE
Quickly move to directory by drag&drop file to "Songs" list

### PR DESCRIPTION
**Pull request by hongquan**
This is primarily used in Ex Falso

### CODE REVIEW

**Comment by declension** [comment]
I'm not quite sure of the motivation behind this change. Is this addressing an existing bug?

Why is this primarily Ex Falso?

**Comment by hongquan** [comment]
@declension I hope these pictures can explain well:

ex falso_112

selection_113

**Comment by lazka** [comment]
You can already drag files/folders to the folder treeview the the top.

**Comment by hongquan** [comment]
> You can already drag files/folders to the folder treeview at the top.

Oh, I'm not aware of it. Will close this PR.

**Pull request closed without merging**
