### PR TITLE
🎨 Some leftover tidying of advanced prefs pane

### PR DESCRIPTION
**Pull request by declension**
See #4411, now rebased to bits that already achieved

* Inherit from VBox like other panes, makes life a bit simpler
* Tweak padding to match a bit more
* Use customised config Switch, reduces duplication
* Left align labels for consistency with other prefs panes
* Remove some redundant code

### Looks like
image

### CODE REVIEW

**Comment by jej** [comment]
Cool.

But labels are left-aligned now, not sure it's more accessible...

**Comment by declension** [comment]
> Cool.
> 
> But labels are left-aligned now, not sure it's more accessible...

Yeah. I think consistency is still the win here though.

Also, newer GTK does this everywhere (including Accessibility prefs!)

image

**Comment by jej** [comment]
No more introduction message after your merge. Is it intentional?

Before:
screenshot_20231025-190200

After:
screenshot_20231025-190803

The message could be modified to be more explicit. IMO it makes the GUI in this pane a little more dressy...

Firefox has this kind of page for about:config

screenshot_20231025-190344

**Comment by declension** [comment]
Yes - that was intentional - that sentence wasn't adding anything new. I would happily add a graphic if someone wants to come up with one (and that Firefox one is new after all)

**Comment by jej** [comment]
Not so new...

FF screenshot

**Pull request merged**
