### PR TITLE
Scale player volume properly in mpris2 API

### PR DESCRIPTION
**Pull request by luk1337**
* This fixes an issue where KDE Connect Android app
  is showing different volume than Quod Libet GUI.

### CODE REVIEW

**Comment by lazka** [comment]
We use a different scaling for the UI slider. If KDE Connect uses a different one there might be a difference.

**Comment by luk1337** [comment]
Well, I copied these magic calculations from `quodlibet/build/lib/quodlibet/qltk/controls.py` so I assumed that it's not KDE Connect's fault but Quod Libet's.

**Comment by luk1337** [comment]
Btw `quodlibet/build/lib/quodlibet/ext/events/mpdserver/main.py` does the very same thing. See https://github.com/quodlibet/quodlibet/blob/22190604238d9d04afb6cb728bc1a4416a17bae6/quodlibet/quodlibet/ext/events/mpdserver/main.py#L273 https://github.com/quodlibet/quodlibet/blob/22190604238d9d04afb6cb728bc1a4416a17bae6/quodlibet/quodlibet/ext/events/mpdserver/main.py#L311

**Comment by luk1337** [comment]
I also tested https://github.com/acrisci/playerctl and after these changes it's able to get and set proper volume.

**Comment by lazka** [comment]
> Btw `quodlibet/quodlibet/quodlibet/ext/events/mpdserver/main.py` does the very same thing. See

Heh, yeah, see 44aa244408ae. I guess I was similarly annoyed by the scale mismatch :)

MPRIS is a bit different as there are many clients and we can't just expose non-linear volume as a linear one. It might improve things with your client but break things with other clients applying a scaling themselves.

**Comment by lazka** [comment]
> Heh, yeah, see [44aa244](https://github.com/quodlibet/quodlibet/commit/44aa244408aef31236a22e145dfc31565b14ca06). I guess I was similarly annoyed by the scale mismatch :) I should have filed a bug with mpdroid instead. :/

Ah, that's because mpd exposes the internal pulseaudio volume directly, so this is more of a workaround for a mpd bug.

**Comment by luk1337** [comment]
Uhm, so what clients are known to work with linear volume?

**Comment by lazka** [comment]
I've opened an issue for the MPRIS spec: https://gitlab.freedesktop.org/mpris/mpris-spec/issues/8

**Comment by jonaski** [comment]
@lazka Did you ever receive any reply form the MPRIS2 folks?
I recently implemented volume synchronization Strawberry and would like to know if I should use linear or cubic for MPRIS2, I have been using linear until now. All other players I tested uses cubic in MPRIS2, but I assume this might be because these are all GTK and they have cubic volume slider for the GUI. The advantage with using cubic is that it will match the percent in the PulseAudio volume control.

**Pull request merged**
