### PR TITLE
Waveform user friendly color pick

### PR DESCRIPTION
**Pull request by urielz**
Adds the ability to change the elapsed and remaining colors of the waveform via a user-friendly color palette

### CODE REVIEW

**Comment by lazka** [comment]
Two observations, not sure if important:

1) First opening the plugin preferences, the color shown in the button and the color used don't match
2) This removes the ability to select the default theme colors

**Comment by urielz** [comment]
Thanks for the comments @lazka. I'll look into that. I'll also add a button to reset the colors to default.

**Comment by urielz** [comment]
Default theme colors is now an option. 

On my end it seems that colors match at first opening the plugin preferences. @lazka Would you mind checking again?

**Comment by lazka** [comment]
Default switches it to red/black here and not the theme colors. Something is wrong with the preferences, they increase the preference window width a lot now for no apparent reason.

**Comment by urielz** [comment]
Ah I see. I didn't know that different themes have different default colors. I'll take a look at that and the width problem as well. Thanks for the feedback @lazka

**Comment by lazka** [comment]
Maybe a checkbox with "Use theme colors" which makes the color picker insensitive would be a solution.

**Comment by lazka** [comment]
Feel free to reopen / create a new one.

**Pull request closed without merging**
