### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [quodlibet/quodlibet](https://hosted.weblate.org/projects/quodlibet/quodlibet/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by jej** [comment]
In the French translation, all "queue" are replace by "playlist". I am not sure of the need for that... It's two different things.
"file d'attente" is like "queue list". Replaced by "liste de lecture", which is like "playlist".
Would you replace all the "queue" by "playlist" in the English language?

**Comment by Bundy01** [comment]
@jej:
I am sorry for the inconvenience. I corrected 'file d'attente' to 'liste de lecture' after a suggestion on Weblate :/

**Comment by lazka** [comment]
@Bundy01 I hope you don't mind my reverting your changes :/ I wasn't sure how to best deal with it. I'll leave a comment on weblate in the future.

**Comment by Bundy01** [comment]
@lazka No problem.

**Comment by lazka** [comment]
@Bundy01 Is French your first language? I see all your changes are unchanged copies from deepl.com. Not that deepl is bad, but it makes me wonder.

**Comment by Bundy01** [comment]
@lazka Yes, i am French. I have trusted the author of the comment, I will be more careful in the future. Sorry :)

**Comment by jej** [comment]
Happy end! Thanks all :)

**Pull request merged**
