### PR TITLE
Refactor gettext code

### LINKED ISSUE #3736: CI: Fedora job now breaking on xgettext issues
Steps to reproduce
------------------
* Take a generally working commit / branch
* Run a build

Expected Output
---------------
No breakage.

Actual Output
-------------
Fedora job dies consistently: 

e.g. Pipeline https://github.com/quodlibet/quodlibet/actions/runs/987582513
e.g. [similar Fedora job in branch pipeline](https://github.com/quodlibet/quodlibet/runs/2978770091?check_suite_focus=true)
 
```
>                       raise GettextError(stderr
                                           or ("Got error: %d" % p.returncode))
E                                          gdist.gettextutil.GettextError: xgettext: .venv/bin/rst2html5.py:2: Unknown encoding "utf8". Proceeding with ASCII instead.
E                                          xgettext: Non-ASCII character at /github/workspace/.venv/bin/rst2html5.py:3.
E                                                    Please specify the source encoding through --from-code or through a comment
E                                                    as specified in https://www.python.org/peps/pep-0263.html.

gdist/gettextutil.py:145: GettextError
=============================== warnings summary ===============================
tests/test_po.py::test_potfile_format
tests/test_po.py::TPot::test_ellipsis
  /github/workspace/gdist/gettextutil.py:148: GettextWarning: xgettext: warning: a fallback ITS rule file '/usr/share/gettext-0.21/its/metainfo.its' is used; it may not be in sync with the upstream
  xgettext: warning: a fallback ITS rule file '/usr/share/gettext-0.21/its/metainfo.its' is used; it may not be in sync with the upstream
  
    warnings.warn(stderr, GettextWarning)
```

### PR DESCRIPTION
**Pull request by declension**
* Use `pathlib` paths everywhere. It's neater now and we get better checking
 * Add lots of typing, mypy does some work for us now
 * Use f-strings for great win
 * Fix some inappropriate test naming...
 * Improve some old / incorrect docstrings
 * Add some tests around `setup.py` PO commands (this broke them initially, but no tests broke)

Fixes #3736

### CODE REVIEW

**Comment by X-dark** [comment]
Seems I cannot build with that change. Is this maybe because of a missing dep?

```
Traceback (most recent call last):
  File "/build/quodlibet-git/src/quodlibet-git/setup.py", line 131, in <module>
    main()
  File "/build/quodlibet-git/src/quodlibet-git/setup.py", line 127, in main
    setup(**setup_kwargs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/build/quodlibet-git/src/quodlibet-git/gdist/po.py", line 260, in run
    basepath = self.build_base / "share" / "locale"
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by declension** [comment]
Thanks @X-dark, my bad; guess I missed those. Moved to #3743

**Comment by lazka** [comment]
this made paths in quodlibet.pot absolute somehow

**Comment by lazka** [comment]
fixed in e6dc1ed67f0ba346220d

**Pull request merged**
