### PR TITLE
Queue stop once empty: do check at end of song instead

### PR DESCRIPTION
**Pull request by frestr**
Stops playback directly when a song has ended and the queue is empty, as opposed to enabling the "Stop After Empty" setting when the last song has started.

See #2774

### CODE REVIEW

**Comment by catmatist** [comment]
Interesting. What if you play a song directly, not going through the queue? With this change, will Quodlibet honor the "stop if queue is empty" flag when that song ends, or does that situation bypass this code entirely? I'll try to find time to figure out how to pull this from GitHub and test it, but it might take awhile as I'm new to this site.

**Comment by frestr** [comment]
As it is now, playing a song directly will not bypass the setting. When I come to think of it, this is exactly the same as how Repeat>One Song works, so this is not really desirable.

IMO, playing a song directly should bypass the setting, while it is honored as long as you are playing from the queue. This makes it so that the setting doesn't have to be disabled when not playing from the queue.

If you want to test it, you can follow the instructions at [Creating a Development Environment](https://quodlibet.readthedocs.io/en/latest/development/devenv.html). The only difference will be that instead of cloning the main repo (`git clone https://github.com/quodlibet/quodlibet.git`), you'll have to clone my fork of it (`git clone https://github.com/frestr/quodlibet.git`) and change to the queue_stop_fix branch (`git checkout queue_stop_fix`) inside the cloned repo.

**Comment by catmatist** [comment]
This is so frustrating! You had it working the way I wanted, and then when I asked how it worked, you changed it and made it useless. Or at least, that is the case if I have understood what you have said about how each version works. Does no one understand the idea that whenever possible, options should have the effect they say they have, and not something subtly different instead? Do I have to check and see if the "one song" option has no effect when songs are playing from the queue? Because the effect I was looking for was exactly that to play more than one song, I can add them to the queue, but if I just "play" a song, Quodlibet does not go on to play some other song that I did not tell it to play.

**Comment by frestr** [comment]
See my reply at #2774

**Pull request merged**
