### PR TITLE
Support ReplayGain in mp4

### PR DESCRIPTION
**Pull request by bp0**
Now QL and the QL ReplayGain Scanner will read and write ReplayGain tags from mp4/m4a files in the format used by the foobar2000 and deadbeef media players. There are no standard ReplayGain tags for mp4, it is simply the flac/vorbiscomment named tags and data format as mp4 freeform tags. 

This is not support for Apple's "SoundCheck" iTunNorm tag.

### CODE REVIEW

**Comment by lazka** [comment]
Please make sure `./setup.py quality` passes.

Also tests would be nice, see `tests/test_format_mp4.py`

**Comment by bp0** [comment]
Now passes ./setup.py quality, although it passed locally even with those trailing spaces, so that is strange.
Added _assert_tag_supported() tests for each of the four tags.

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
> Now passes ./setup.py quality, although it passed locally even with those trailing spaces, so that is strange.

Probably because pep8 or pyflakes wasn't installed and it skipped those tests. I've made it more strict now in  c4d4f4dd79d

**Pull request merged**
