### PR TITLE
Reverse DNS app ID

### PR DESCRIPTION
**Pull request by fkrull**
See issue #2792. I renamed everything I could find that needs to match the Flatpak app ID, in particular:

* the desktop file
* the appdata file
* the D-Bus names
* the application icon
* the GNOME search provider

This does mean the `net.sacredchao.QuodLibet` D-Bus name goes away. Any third-party clients using that name that may or may not exist would have to be updated.

I also added `StartupWMClass` to the desktop file. Without it, Unity had difficulties matching the window to the desktop file.

I left Ex Falso alone for the moment.

### CODE REVIEW

**Comment by lazka** [comment]
Thanks!

Can your revert the "quodlibet/quodlibet/qltk/dbus_.py" changes?

I'd prefer if it just gets blocked in flatpak (is that a problem?), and once we move MPRIS into the core we might drop it altogether.

**Comment by fkrull** [comment]
I played around with it and it turns out that yes, I can. ;) I left the other D-Bus names (search provider and the app menu) as-is since no one should write those names down and talk to them.

**Comment by lazka** [comment]
Thanks :)

**Comment by CreamyCookie** [comment]
Regarding the icon, it seems that with this change, every icon pack ([Numix Square](https://github.com/numixproject/numix-icon-theme-square), for example) has to create a symlink from "quodlibet" to "io.github.quodlibet.QuodLibet". It's not a big hassle, but is that change necessary?

**Comment by lazka** [comment]
> It's not a big hassle, but is that change necessary?

afaik we could have only done it for the flatpak build, but then you would have two names depending on how things are installed. But maybe I've missed something?

**Comment by fkrull** [comment]
> afaik we could have only done it for the flatpak build, but then you would have two names depending on how things are installed

Well, there's no way to *not* rename the icon for Flatpak. Having both names sounds like a maintenance nightmare to me, especially considering how many places this PR ended up touching. Also, any icon theme would have to support both names anyway if they want to work for Flatpak installations.

**Comment by CreamyCookie** [comment]
Makes sense! I'm looking forward to flatpak support. =)

**Comment by lazka** [comment]
> Makes sense! I'm looking forward to flatpak support. =)

No need to wait :) https://flathub.org/apps/details/io.github.quodlibet.QuodLibet

**Pull request merged**
