### PR TITLE
Create Tagging

### PR DESCRIPTION
**Pull request by John-Peters**
I am using version 3.7.1 Linux version (Ubuntu 64 bits).
I have two questions:
When I create tags from the file name, how can I remove the file extension?
After adding the album photo how do I save it for all files in the album?
Thanks for your help

### CODE REVIEW

**Comment by lazka** [comment]
>  When I create tags from the file name, how can I remove the file extension?

It should be removed automatically. Can you give an example for a filename and the tag pattern?

>  After adding the album photo how do I save it for all files in the album?

In case you are referring to embedding the image in the files:

There is a "Edit Embedded Images" plugin which, if activated, exposes the follow context menu item: "Edit Embedded Images" > "Embed Current Image"

**Comment by John-Peters** [comment]
Merci pour votre aide.
En fait, le problème semble être que quand je clique sur "aperçu" il ne se passe rien......
Je vous joins la capture d'écran
etiquettes par chemin

**Comment by John-Peters** [comment]
Sorry, I'll start again in English ...!!
In fact the problem seems to be that when I click on Preview I don't see anything happen.
I attach the screen image
John Peters

**Comment by lazka** [comment]
Try `<tracknumber> <title>` instead. The format in the text entry at the top has to match the format of the filenames.

**Comment by John-Peters** [comment]
Same situation. Must be something basic I haven't understood....
capture

**Comment by lazka** [comment]
Make sure there is only one space between `<tracknumber>` and `<title>`

**Comment by John-Peters** [comment]
OK GREAT !!!! I had TWO spaces. With one space it works fine.
Many thanks

**Comment by lazka** [comment]
:)

**Comment by John-Peters** [comment]
Here's the screenshot. That's a REALLY useful feature. Thanks
capture ok

**Pull request closed without merging**
