### PR TITLE
Fix --show-window description in man page

### PR DESCRIPTION
**Pull request by SimonLarsen**

### CODE REVIEW

**Comment by lazka** [comment]
Thanks. These files are generated and they shouldn't be changed manually. The source is here: https://github.com/quodlibet/quodlibet/tree/master/quodlibet/docs/guide/commands ; the make file generates the man pages

**Comment by SimonLarsen** [comment]
Oh yeah, of course. Changed the source file and ran make. Should be okay now.

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Added a readme now: 0085ff4e4ae359d7a613

**Pull request merged**
