### PR TITLE
Add Soundcloud browser

### PR DESCRIPTION
**Pull request by declension**
See #1828 for background.

This collection of, err, ~~40~~ 34 (+ merge) commits is what hopefully now represents a minimum viable (and compliant, as far as my checks have gone) feature for Soundcloud, plus a bunch of "free extras" I did along the way (see checklists in #1828).

The technical commentary is generally in the various detailed commit messages (so please don't squash).

Seems working from here now, but probably contains a few bugs / inefficiencies / gotchas still so it would be good to validate this on a few different systems. Features / improvements can be added in later PRs, as this one has got far too big really... :wink:

### CODE REVIEW

**Comment by lazka** [comment]
Two blockers imo, but if that's get handled after merge, fine with me.

* I don't think we can ship the icons
* Does the login still depend on a custom URI scheme? We need something that works on OSX/Windows.

**Comment by declension** [comment]
Thanks

>    I don't think we can ship the icons

Ah, yes that. What's the specific concern - GPL? Conversely, SC seems to be quite keen on _always_ displaying the icons (["If you are using SoundCloud's data in your app or site, we ask that you place these logos where the data is being used/shown"](https://developers.soundcloud.com/docs/api/buttons-logos) etc). Might need to look at that web-caching idea you had then...

>    Does the login still depend on a custom URI scheme? We need something that works on OSX/Windows.

It still uses it where available (it's definitely a UX win), but I added a third state for the button (logging in) whereby you can enter the code manually copied from the redirect page (even pastes it from the clipboard by default). This should allow all users then, but I think the OS X registration might be doable too

**Comment by lazka** [comment]
>>    I don't think we can ship the icons
>
>Ah, yes that. What's the specific concern - GPL? Conversely, SC seems to be quite keen on _always_ displaying the icons (["If you are using SoundCloud's data in your app or site, we ask that you place these logos where the data is being used/shown"](https://developers.soundcloud.com/docs/api/buttons-logos) etc). Might need to look at that web-caching idea you had then...

A Gtk.Image subclass which does an async http request shouldn't be too hard. I can look into that if you want.

>>    Does the login still depend on a custom URI scheme? We need something that works on OSX/Windows.
>
> It still uses it where available (it's definitely a UX win), but I added a third state for the button (logging in) whereby you can enter the code manually copied from the redirect page (even pastes it from the clipboard by default). This should allow all users then, but I think the OS X registration might be doable too

Yeah, I've used the manual code input. But once you log in it redirects you to a browser error page, and you have to figure out that part of the URL has to be copied to QL. No UX win in that case.

**Comment by declension** [comment]
Redirect problem resolved in https://github.com/quodlibet/quodlibet.github.io/commit/f4892bdb485d83b3cd22d1e9105f25b46bfca5b0

**Comment by declension** [comment]
> A Gtk.Image subclass which does an async http request shouldn't be too hard. I can look into that if you want.

@lazka that would be great, if you have time

**Comment by lazka** [comment]
here is a basic implementation: https://gist.github.com/lazka/87b59993b3cf01ed420d78dda03e1eac

**Comment by lazka** [comment]
Nice, one more thing: As the images are defined globally the http requests happen on every QL start, even if another browser is selected.

Either move them locally, or use our ``@cached_func`` decorator.
Or we could only start loading them when the mapped in screen, but I'd prefer the first solution as I'd like to avoid creating Gtk.Widget instances at import time.

**Comment by lazka** [comment]
Sorry for the conflicts.

Feel free to merge

**Comment by declension** [comment]
No worries - merging then :)

**Pull request merged**
