### PR TITLE
Advanced preferences plugin

### LINKED ISSUE #1050: Add plugin to tweak inaccessible config settings
Original [issue 1050](https://code.google.com/p/quodlibet/issues/detail?id=1050) created by nick.boultbee on 2012-11-01T21:18:44.000Z:

After Issue #892, it seems a shame not to allow some common options to be selectable without manually editing config.

Some potentials to be included:
 ♪ (eighth note U+266A)
 ☆ (white star, U+2606)
 ★ (black star, U+2605)
 ✶ (six-pointed black star, U+2736)
 ♥ (black heart, U+2665)

### PR DESCRIPTION
**Pull request by brunob**
Work in progress to fix #1050

Not sure if we can use ValidatingEntry + QueryValidator for some entries ?

Todo:
- [x] id3encoding
- [x] search_tags
- [x] disable_hints
- [x] rating_symbol_blank
- [x] rating_symbol_full
- [x] backend

### CODE REVIEW

**Comment by brunob** [comment]
@lazka do you know what type of input should be used for backend pref : simple text input, a select or anything else ?

**Comment by lazka** [comment]
simple text input should be enough

**Comment by brunob** [comment]
I'd like to try adding reset buttons for rating_symbol_ prefs but i can't find a way to do it with the way i'm constructing the table with the for loop :\

**Comment by lazka** [comment]
Sorry for the long delay. Cleaned up and pushed.

**Comment by brunob** [comment]
Thx a lot for the refactoring @lazka :)

**Pull request merged**
