### PR TITLE
Update Norwegian bokmål (nb) translation

### PR DESCRIPTION
**Pull request by koratfood**
Check-list
----------

 * [ ] There is a linked issue discussing the motivations for this feature or bugfix
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [x] Performance seems to be comparable or better than current `main`

What this change is adding / fixing
-----------------------------------
Complete translation to Norwegian bokmål (nb) as of current POT.

### CODE REVIEW

**Comment by declension** [comment]
FYI we now use [weblate](https://hosted.weblate.org/projects/quodlibet/quodlibet/) for handling all translations

**Comment by koratfood** [comment]
From [docs --> Translation Guide --> How-to (Legacy Manual Process)](https://quodlibet.readthedocs.io/en/latest/translation/howto_manual.html):

> The new preferred method to translate is via [Weblate](https://hosted.weblate.org/engage/quodlibet). The process described here still works and is supported in case you for some reason prefer it.

Are you saying the latter sentence in that quote no longer applies?

**Comment by declension** [comment]
No I _think_ it's still all fine, just noting that nobody has used it now for some time,  so can't guaranteed that.

Probably @lazka knows better

**Comment by lazka** [comment]
It should still work. There is a higher chance of conflicts if updates happen in both places at the same time, but that doesn't seem to be the case here.

**Comment by declension** [comment]
Cool I guess we can merge this as-is then?

**Pull request merged**
