### PR TITLE
New plugin to send a stop signal to the player backend on pause

### PR DESCRIPTION
**Pull request by othalan**
This is a plugin to workaround issue #2771, which appears to be a fault in the audio backend.

The basic problem solved by this plugin:

On macOS, play music through the system speakers then connect a bluetooth speaker.  Typically audio output will transition to the new bluetooth speaker.  However, QoudLibet and other media players using the gstreamer backend will not transition to the new bluetooth speaker (or other audio output device) as expected.  This behavior has also been observed in other media players using gstreamer, such as Clementine player.

In order to provide a workaround for this problem, this plugin will detect Pause events and send a stop signal to the backend player.  This relies on the fact that the gstreamer backend will destroy the current pipeline when stop() is called. 

In order to maintain current functionality to the best extent possible, the plugin attempts to seek to the same playback position after stopping playback, thus emulating pause functionality.  If the stream reports it is not seekable, playback is left stopped.  An option in the plugin can be set to only enable this functionality for seekable sources (in order to ensure playback position is not lost by using this plugin).

### CODE REVIEW

**Comment by othalan** [comment]
It occurs to me I should note that the VLC backend I am working on (see #2845) will also provide a solution to this same bug.  I have submitted this plugin for two reasons:  First, for the record that this solution is available (I have been using it for months), and second because using VLC as a backend may not be desirable for some people.

**Comment by lazka** [comment]
What about just restarting QL instead? It should restore all state and I don't think anyone hitting the same problem as you would figure out that this plugin will fix it.

**Comment by othalan** [comment]
@lazka, restarting QL is an option.  However, doing so was enough of a nuisance that I took the time to create this plugin to work around the problem.  The two annoyances with restarting QL are first, the extra time involved waiting for shutdown and restart, and second that I use virtual desktops to keep my apps organized and must ensure QL opens where I want it to.  Minor, I admit, but annoying.

In truth, I'm not certain I'd include this plugin in your position, especially if the VLC backend is merged in. But I wanted to offer it for the sake of it being available and referenced in the issue.  It occurs to me, this plugin would be more appropriate in a list of available plugins that can be downloaded separately.

Out of curiosity, why not include a "stop" button in the GUI?  That provides a workaround most users discover on their own.

**Comment by bassstorm** [comment]
I'd love to have Stop button. Because, sometimes I really want to... actually **stop** playback.

**Comment by rogatty** [comment]
Can this PR be merged? I just hit the issue with bluetooth headphones and would love to have this workaround available.

**Comment by pklampros** [comment]
The added benefit of this plugin is that with it, QL actually allows bluetooth headphones to go to sleep if left on and unused because it lets go of the sound interface.

**Comment by declension** [comment]
Cleaning up old PRs.

Seems like a good workaround to several users' audio problems. Perhaps we can fix the conflicts, rebase / merge from master and try it out (CC @lazka)?

**Comment by bassstorm** [comment]
Would be really nice to have. I already experienced that unpleasant audio output change behavior on macOS :smiley:

**Comment by othalan** [comment]
> Cleaning up old PRs.
> 
> Seems like a good workaround to several users' audio problems. Perhaps we can fix the conflicts, rebase / merge from master and try it out (CC @lazka)?

I am not currently using QuodLibet, however I realize the utility of this plugin as it was critical to my own use when I did use QuodLibet as my music app. I have  done my best to rebase the plugin and fix problems so that it can be merged.

**Comment by declension** [comment]
Thank you @othalan !

**Pull request merged**
