### PR TITLE
Consistent ending punctuation for multi-sentence tooltips

### PR DESCRIPTION
**Pull request by Mellthas**
See discussion in #3209. The second commit tries to retain existing translations, similar to #3215.

### CODE REVIEW

**Comment by Mellthas** [comment]
`test_po.py` now fails for `ru.po`, because the translation does not end in a period (`test_original_punctuation_present`). It is only a single sentence though, so I think a legitimate difference from the source string.

**Comment by CreamyCookie** [comment]
I think lines ending with a pattern is an edge case where I personally prefer no period since it looks a bit too noisy. (And a new user might wonder if the dot is part of the pattern.)

`Accepts QL Patterns e.g. <~artist~title>` 
`Accepts QL Patterns e.g. <~artist~title>.`

Also, in the above case isn't that change inconsistent with the previous one to remove periods for simple texts (#3208)?

> test_po.py now fails for ru.po, because the translation does not end in a period

Shouldn't it not also end in a period?

**Comment by Mellthas** [comment]
@CreamyCookie, that is a point, I thought about that, too. Maybe better to just leave these alone. Then the changes would boil down to just the one tooltip in `prefs.py`. I’ll open a competing PR :-).

> Also, in the above case isn't that change inconsistent with the previous one to remove periods for simple texts (#3208)?

No, as this string is only used in combination with two tooltip strings (see line 137 and 141):

```
_("Status text when a song is started.") + ' ' + _ACCEPTS_PATTERNS
_("Text when a song is paused.") + ' ' + _ACCEPTS_PATTERNS
```

**Comment by Mellthas** [comment]
> Shouldn't the translation not also end in a period?

The translation in question is:

`Список разделителей (через пробел), которые будут использоваться для разделения тегов`

which Google translates back to:

`List of delimiters (separated by spaces) that will be used to separate tags`

Which is a bit shorter than the original, and wouldn't use a period at the end (right?):

`A set of separators to use when splitting tag values in the tag editor. The list is space-separated.`

**Comment by declension** [comment]
@Mellthas That Russian sounds like a direct translation of the old version of that string (IIRC)

**Comment by Mellthas** [comment]
I added another commit which reverts the change to the Russian PO file, to make the tests pass.

**Comment by Mellthas** [comment]
For the future, it might be good to have a look at the PO tests. The ending-punctuation test (`test_original_punctuation_present`) is only run for the Russian and German PO files. I looked up the origins of the test, #1509 has some background on the difficulty of enabling it for more languages. It might make sense to make these checks optional, but allow them to be run for any language. Using poedit, I get a warning for an ending punctuation mismatch, but I can decide to ignore that. The checks are more comprehensive, so e.g. it also warns on an ending period in the translation if the source string does not have one.

If I find some time, I can take a look at that.

**Comment by CreamyCookie** [comment]
> It might make sense to make these checks optional, but allow them to be run for any language. 

@Mellthas I don't know enough about the translation tools, but that sounds like a good idea. Anyway, I'm closing this. (The alternative was merged.)

**Comment by Mellthas** [comment]
Thanks. Just for the reference, Translate Toolkit (https://github.com/translate/translate) looks quite promising. It has the ability to check PO files with a multitude of filters (e.g. http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/pofilter_tests.html#endpunc for ending punctuation).

**Pull request closed without merging**
