### PR TITLE
Create a new VLC backend

### PR DESCRIPTION
**Pull request by othalan**
This pull request is for a new VLC backend as discussed in issue #2845.  This provides a workaround for Issue #2771 and potentially other gstreamer related issues.  The README file from the new code is included below.

**Two significant notes for the pull request:**

1. The PIP package python-vlc must be installed!
  - For MacOS and Windows, this should be part of the distribution package.  This is a single file and so should be easy to include.
  - For Linux, this should probably be set as an install dependency and handled by the package manager.
    - Alternatively, on linux, installation of python-vlc could be up to the user and instructions added to the README file for the backend.
2. I have not created any automated tests at this time because testing would require installing the VLC application.

README FILE CONTENT
==================

VLC Backend
===========

VLC is an open source media player with a reputation for reliability, high quality algorithms, and robust support for audio and video formats. The VLC project automatically generates bindings which permits VLC to be embedded within other applications. These bindings permit VLC to act as a backend player to the Quod Libet application by simply ignoring the video fuctionality.

VLC Backend Benefits
====================

Using VLC as a backend has numerous potential benefits.  The driving benefits behind the creation of this new backend for Quod Libet include:

- Lower CPU utilization
- Improved sound quality in some situations
- Automatic detection of new audio output devices on MacOS

VLC Backend Limitations
=======================

Using VLC as a backend has a few limitations

- The VLC application must be installed separately
- Gapless playback is not supported

Using the VLC Backend
=====================

Using the backend has two setup requirements:

1. Install the VLC media player:
   - https://github.com/videolan/vlc/releases

2. Setup Quod Libet to use the VLC backend:
   - Edit the VLC configuration file (e.g. `~/.quodlibet/config`)
   - Find the section marked `[player]`
   - Set the backend as follows (change an existing line or add a new line as necessary):
     - `backend=vlcbe`

VLC Links
=========

VLC Project: https://github.com/videolan/vlc
VLC C Bindings API: https://www.olivieraubert.net/vlc/python-ctypes/doc/
VLC Python Bindings Wiki: https://wiki.videolan.org/python_bindings

In order to interface with the VLC libraries, this code relies on the auomatically generated python bindings for VLC which are available at these locations:

PyPi: https://pypi.org/project/python-vlc/
Videolan: http://git.videolan.org/?p=vlc/bindings/python.git;a=tree;f=generated;b=HEAD

### CODE REVIEW

**Comment by othalan** [comment]
All functionality is complete with two limitations:  The Quod Libet equalizer interface cannot set preamp values and cannot load presets from a backend.  FIXME notes on these features have been added to the code.

**Comment by othalan** [comment]
It seems the 'continuous-integration' check is failing in code not related to this pull request ....

**Comment by lazka** [comment]
> It seems the 'continuous-integration' check is failing in code not related to this pull request ....

yes, fixed in c6fcf7674adc, rebasing should fix it

**Comment by declension** [comment]
Are there any plans to continue (and maintain) this, or shall we close?

**Pull request closed without merging**
