### PR TITLE
Connect TreeViewHints->view leave-notify-event to __undisplay

### PR DESCRIPTION
**Pull request by luk1337**
Check-list
----------

 * [x] There is a linked issue discussing the motivations for this feature or bugfix
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [ ] Performance seems to be comparable or better than current `main`

What this change is adding / fixing
-----------------------------------

This fixes stuck tooltips when leaving the window.

See: https://www.youtube.com/watch?v=x7Ey-y0TPIs
Closes: #4259

### CODE REVIEW

**Comment by declension** [comment]
Thanks!

**Comment by lazka** [comment]
I had to revert this as it broke tooltips on Windows -> 08a09735acf306c3022c9b1

**Comment by luk1337** [comment]
> I had to revert this as it broke tooltips on Windows -> [08a0973](https://github.com/quodlibet/quodlibet/commit/08a09735acf306c3022c9b12fd032b8e644b6119)

Do you have any idea how else this could be solved?

**Comment by nemethf** [comment]
> > I had to revert this as it broke tooltips on Windows -> [08a0973](https://github.com/quodlibet/quodlibet/commit/08a09735acf306c3022c9b12fd032b8e644b6119)
> 
> Do you have any idea how else this could be solved?

Would something along these lines be acceptable?

```python
if is_windows():
   # See issues #4259, #4365
    view.connect('leave-notify-event', self.__motion),
else:
    view.connect('leave-notify-event', self.__undisplay)
```

**Pull request merged**
