### PR TITLE
Icon relooking proposal

### LINKED ISSUE #3890: Icon relooking proposal
Hi all,

I propose a hot topic today!

The proposed change
-------------------
I have been using QL for a short time, but the first thing I did was to relook the icon, after I tested QL a bit and felt this software was promising for my music management. I did this because I use a black background dock and it was difficult to see the QL icon.

old-icon-dock

An old issue exists (#3628) but maybe it's a never-ending subject to create a logo from scratch.

So after some thinking about the current icons, I did a relooking that preserve the current history. In fact I don't know who did the icons, and if it was a real design work or just a quick drawing that has survived the ages. Sorry if the original author doesn't like my changes.

The changes:
- I took the VSCodium icon as template concerning dimensions and round design.
- the color of the circle comes from the current twitter logo. https://twitter.com/QuodLibetApp
capture_ecran_20220111-200004
- the note's "head" is filled. Because a note with a hole brings details to the logo, that does not stretch well. It makes more confusion when down sizing. The same apply for the symbolic icon.
- a light shadow for the pictogram.

- ExFalso icon is relooked in the same spirit. A 12° rotation make it a bit more dynamic.
- Favicon slightly relooked (head filled)
- Symbolic icons relooked like the main icons.

Main icons:
io github quodlibet QuodLibet
capture_ecran_20220111-210511

io github quodlibet ExFalso
capture_ecran_20220111-210445

Symbolic icons:
io github quodlibet QuodLibet-symbolic
io github quodlibet ExFalso-symbolic

The symbolic icon in the topbar (old vs new):
menubar

The favicon of the doc (old vs new):
favicon

The QL icon in situation:
new-icon-dock

Hope you will like it. Possible to test here: https://github.com/jej/quodlibet/tree/icon-relooking-proposal
You have to `./setup.py install` to install the icons in your OS. Then for gnome desktop ALT+F2 & `r` to reload the desktop and see the icons.

See #3889 for the commit.

Benefits of this change
-----------------------
Maybe too subjective topic to tell more here...

Any issues this might cause
---------------------------
- Icons are technically the same, so they should not cause any trouble.
- Icons are graphically close to the current one. Old icon and new would not make a big difference for a soft transition. At a first glance, new and old are the same because pictogram are almost the same.
- Perhaps the original author might be upset by these changes, although the icon remains quite identical in spirit.

### PR DESCRIPTION
**Pull request by jej**
Check-list
----------

 * [x] There is a linked issue discussing the motivations for this feature or bugfix
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [x] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------
Fixes #3890

### CODE REVIEW

**Comment by jej** [comment]
PS:
2 files seem orphan...
`images/hicolor/scalable/apps/io.github.quodlibet.QuodLibet-symbolic.svg.in`
`images/hicolor/scalable/apps/io.github.quodlibet.ExFalso-symbolic.svg.in`

**Comment by declension** [comment]
@lazka any opinions?

**Comment by lazka** [comment]
> `images/hicolor/scalable/apps/io.github.quodlibet.QuodLibet-symbolic.svg.in`
> `images/hicolor/scalable/apps/io.github.quodlibet.ExFalso-symbolic.svg.in`

They shouldn't be: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/images/Makefile#L13 They are the source for the symbolic icons.

> @lazka any opinions?

Fine with me in general. I'd prefer a bit more even padding inside the circle on the QL logo even if it isn't centered then. And the EF could use some padding inside the circle as well. my 2c.

**Comment by declension** [comment]
> Fine with me in general. I'd prefer a bit more even padding inside the circle on the QL logo even if it isn't centered then. And the EF could use some padding inside the circle as well. my 2c, ymmv.

Thanks, and yes +1 to more padding actually @jej

**Comment by jej** [comment]
> They shouldn't be: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/images/Makefile#L13 They are the source for the symbolic icons.

Ok, got it. The inkscape -f option is obsolete. So I was working on .svg files, ignoring the .in was the source...

**Comment by jej** [comment]
With some more padding:
capture_ecran_20220117-134012
capture_ecran_20220117-134010
capture_ecran_20220117-134536



It's still a bit less padding than the twitter icon.

**Pull request merged**
