### PR TITLE
ID3: Use TPE2 for Album Artist and a TXXX tag for Performer

### LINKED ISSUE #1179: ID3: Use TPE2 for Album Artist and a TXXX tag for Performer
Original [issue 1179](https://code.google.com/p/quodlibet/issues/detail?id=1179) created by derVedro on 2013-06-11T21:48:01.000Z:

Hi, I saw that Album Artist taged mp3 files doesn't showed correctly in Clementine and EasyTag. May be it is better to use TPE2?

### PR DESCRIPTION
**Pull request by muusik**
fixes #1179

### CODE REVIEW

**Comment by declension** [comment]
Hmm, no problems with the idea, but some kind of migration script to move existing libraries across might be good.

...or at least a warning to users about this change and the impact it will have on their libraries.

**Comment by lazka** [comment]
Yeah, we need a strategy for migrating things... :/

**Comment by zsau** [comment]
#48 needs a migration strategy as well. Tag mapping versioning (#1590) is an option, but sounds complex. I'd favor a user-activated migration script (plugin?) and a message about the change.

**Comment by fdw** [comment]
Has there been any progress regarding the migration strategy? Would it be enough to move the content of the "albumartist" tag to TPE2 programmatically, or am I missing something?

**Comment by declension** [comment]
Unfortunately no progress on the tag migration. 

Given this PR no longer merges I propose we close until we have a way of doing this unless anyone strongly objects...

**Pull request closed without merging**
