### PR TITLE
Ignoring characters in queries.

### LINKED ISSUE #3198: Ignore the character "-" on search
The proposed change
-------------------
On any search input fields ignore the character "-" during search.

Benefits of this change
-----------------------
**1.** 
Most if not any music application I know ignores the "-" char during search. This makes it possible to search a song like this: `<Artist> - <Songname>`. 

In my case I am copy pasting very often. Therefore I need to manually remove the "-" sign every single time, which starts to annoy me enough to write this feature request.

**2.** 
The proposed change also prevents users from getting search results not matching the expectation.

Lets say I search `<Artist> - <Songname>`.

The results are:
`<Artist>, <Songname> - Radio Edit`
`<Artist>, <Songname> - Club Edit`

I get all results containing "-" somewhere in the text itself. 

But I wanted to find the original song. This is annoying since it requires another search. I have a huge library, this every time takes a few seconds.

Any issues this might cause
---------------------------
Don't see any.
Usability isn't decreased since this is the expected behaviour in my opinion.

### PR DESCRIPTION
**Pull request by blimmo**
Closes #3198 

I've erred on the side of caution and only done the ignoring on text queries.

I've also gone for a default of no ignoring since I think it's easier to notice that you want to ignore a character than to notice you don't (after having a query inexplicably not work for example).

### CODE REVIEW

**Comment by CreamyCookie** [comment]
Looks good (though I don't know enough about the query system to be sure), but is this really something that should be in the main preferences. I think this would fit better into the [advanced preferences](https://github.com/quodlibet/quodlibet/blob/30293621f466cbc0076ed2db703702ef0234a853/quodlibet/quodlibet/ext/events/advanced_preferences.py).

Maybe the query thing also needs tests. (Does it work with queries like `artist=test-test` if `-` is ignored? If not, would that be confusing?)

**Comment by blimmo** [comment]
Wait... There's an advanced preferences?! XD

Yeah putting it there sounds like a good idea, I'll move it there when I have time.

I avoided tests mostly because I wasn't really familiar with the organisation of them and I wasn't sure if this was really a big enough change to warrant them but I can add probably add those too.

**Comment by CreamyCookie** [comment]
Thanks! 

> Wait... There's an advanced preferences?! XD

Yeah, it's a bit hidden since it's currently implemented as a plugin. (If #2156 gets implemented that might change but that will likely happen anytime soon, if ever.)

**Comment by CreamyCookie** [comment]
Looks good to me.

(the one test fail is again caused by IRC connection issues, so unrelated to this pull request)

**Comment by declension** [comment]
> (the one test fail is again caused by IRC connection issues, so unrelated to this pull request)

BTW this should now be fixed (#3241) so meeting from `master` might help here

**Comment by declension** [comment]
I've retried that job nonetheless

**Comment by CreamyCookie** [comment]
@declension Nice, thanks! :)

**Pull request merged**
