### PR TITLE
Quick fix of issue #3872

### PR DESCRIPTION
**Pull request by jej**
Check-list
----------

 * [x] There is a linked issue discussing the motivations for this feature or bugfix
 * [x] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [x] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------
Quick fix for #3872

I noticed this too and I don't know what was the idea behind. It was introduced in 2005: https://github.com/quodlibet/quodlibet/commit/be602696781f947e3d31398ae2742ab00f96a1c6

I find it strange to add a piece of information that says something is missing... Maybe the file name alone is enough.

Hope it helps,
J.

### CODE REVIEW

**Comment by declension** [comment]
I have no strong feelings. Some people might rely (I have at times) on the _Unknown_ to help seeing untagged songs...

@lazka any opinion?

**Comment by jej** [comment]
It's not a big problem for me, everything I listen is tagged. But I am still sensible to illogical gui details... To display "Unknown" (or "Inconnu(e)" in French) is not a really useful information, about what is unknown. Maybe the gui should display an information related to the reason the information is displayed, and not a side effect information like a log/debug information.
So maybe "Untagged track" is better, if this point has to be improved.

**Comment by declension** [comment]
>Maybe the gui should display an information related to the reason the information is displayed, and not a side effect information like a log/debug information.
> So maybe "Untagged track" is better, if this point has to be improved.

Yes that does sound like an improvement actually :+1:

**Comment by jej** [comment]
Yep right, according to the code that's a title concern only.

I am still wondering if it's important to say that a title is missing? :) I have some ripped audio conferences from youteub, and it's not taggued. If I have the mp3 title it's ok.

Maybe an icon for this case could do the job, but don't know what could be this icon? It would be better than a text, because a text may be interpreted as something saved in the track (an idtag containing _Unknown_).

capture_ecran_20220111-131418
More ideas here: https://thenounproject.com/search/icons/?iconspage=2&q=unknown

For now if the code needs a change, something like you say would be ok for me. _(missing title)_ ou _(unknown title)_, without case to don't make it as pretty as a formal title.

**Comment by jej** [comment]
Here an example with unicode char:

capture_ecran_20220111-133702

**Comment by jej** [comment]
> Although I guess it's more _(Missing Title)_ or something (there could be plenty of _other_ tags)

It could be also an advanced option to display or not missing titles...

**Comment by jej** [comment]
Completly lost with git rebase/conflict/etc... WTF! I close and open again?

**Comment by jej** [comment]
Rework in progress...

**Pull request closed without merging**
