### PR TITLE
Minor QuodLibet / ExFalso subtitle change (see #2158)

### PR DESCRIPTION
**Pull request by CreamyCookie**
Minor QuodLibet / ExFalso subtitle change (see #2158)

### CODE REVIEW

**Comment by CreamyCookie** [comment]
Weird, I didn't change the line endings. Maybe we should add a [`.gitattributes` file](https://help.github.com/en/articles/dealing-with-line-endings#per-repository-settings) to make sure consistent line endings are used (and files like *.nist keep crlf)

**Comment by CreamyCookie** [comment]
I'm out of ideas how to fix the line endings. (Have tried `git add --renormalize`, copying the CRFL version into the editor here etc.) Any ideas?

**Comment by lazka** [comment]
Not sure. Make sure "core.autocrlf" isn't enabled (it's not the default) and that your editor doesn't change line endings.

**Comment by CreamyCookie** [comment]
core.autocrlf was set to input but supposedly [`.gitattributes` overrides an individual's core.autocrlf](https://help.github.com/en/articles/dealing-with-line-endings)

I've also tried from the command line (while IDE is closed). I've checked the file has CRLF and Git responds that there is nothing to commit, so CRLF is used.

I have no created a fresh clone (with my branch selected) and CRLF is used. Seems like Git's diff viewer is bugged. (sigh..)

Can this be merged?

**Comment by lazka** [comment]
> I've also tried from the command line (while IDE is closed). I've checked the file has CRLF and Git responds that there is nothing to commit, so CRLF is used.

I think .gitattributes will change things when you check them out, so you will not see what's in the actual repo.

Anyway, I've squashed things in the branch. Feel free to hit the merge button if it still looks ok to you.

**Comment by CreamyCookie** [comment]
Looks good. Thanks!

**Pull request merged**
