### PR TITLE
discord_status: Better handling for details/status

### PR DESCRIPTION
**Pull request by teeleafs**
Check-list
----------

 * [x] There is a linked issue discussing the motivations for this feature or bugfix (#4168)
 * [ ] Unit tests have been added where possible
 * [ ] I've added / updated documentation for any user-facing features.
 * [X] Performance seems to be comparable or better than current `master`

What this change is adding / fixing
-----------------------------------
The "state" and "details" field of Discord Rich Presence cannot handle strings that are less than 2 or more than 128 characters, so pad or truncate as appropriate.

### CODE REVIEW

**Comment by afontenot** [comment]
@teeleafs I believe you should have linked to this issue: https://github.com/quodlibet/quodlibet/issues/4168

Could you please look at my comment there? The way you're doing this (`text[:125] + "..."`) will fail if Discord is counting bytes rather than code points. As I don't have a Discord account, I have no way to check this, but their documentation claims to limit to 128 bytes.

**Comment by teeleafs** [comment]
@afontenot Thanks for the heads-up and the comments. OP posted on the Discord about the bug and we were talking there and I did not realize there was an issue opened. I'll post more on the issue discussion.

**Comment by teeleafs** [comment]
Duplicate of #4168

**Comment by teeleafs** [comment]
I guess someone with write access must mark this as duplicate?

**Comment by declension** [comment]
Shall we close this PR or can the comments be addressed?

**Pull request closed without merging**
