### PR TITLE
Online crash reporting. See #1853

### PR DESCRIPTION
**Pull request by lazka**
Most of the error reporting is now in quodlibet.errorreport

* Logging the error and printing to stdout
* Writing the error + recent logs to disk
* Showing the error to the user
* Opening a pre-filled github issue
* Sending the error sentry.io (github fallback)
* Logging/reporting segfault stacktraces

Depends on raven, which is unlikely to be installed atm, maybe we'll vendor it.

### CODE REVIEW

**Comment by lazka** [comment]
This now includes raven and contextlib2 directly in git and will also install it. They both don't get included in the source tarball and the code falls back to prefilled gihub issues in those cases. Couldn't think of anything better..

raven required quite a bit of monkey patching to get working for our use case, but since we only use the internal version this should be fine I guess.

I consider this mergeable, feedback welcome.

**Comment by declension** [comment]
Good work! All seems to function properly here, though I haven't got the Sentry login to check anything on the other side.

The bit that scares me slightly is the diff: `+14,804 −490 lines`.
Is there a way of pulling `raven` (in a build step maybe), and monkey patching the original one - or is that too tricky (haven't seen the code really)? 

Alternatively is an egg / wheel in Git an option - then there's a cleaner distinction between vendor code and QL code (and devs / IDEs don't see that code so much)? I guess it would still need an explicit build step which is a bit weird for Python (maybe...).

**Comment by lazka** [comment]
> Good work! All seems to function properly here, though I haven't got the Sentry login to check anything on the other side.

Thanks. I'll look into making it possible for more people to see the data.

https://sentry.io/share/issue/3134323431352e323334303630333835/

> The bit that scares me slightly is the diff: `+14,804 −490 lines`.
Is there a way of pulling `raven` (in a build step maybe), and monkey patching the original one - or is that too tricky (haven't seen the code really)? 

Build step would work somehow. The upside now is that we can test it on travis.

> Alternatively is an egg / wheel in Git an option - then there's a cleaner distinction between vendor code and QL code (and devs / IDEs don't see that code so much)? I guess it would still need an explicit build step which is a bit weird for Python (maybe...).

I haven't checked, but zip import might work. Is there any problem with your IDE and the current solution?

See https://github.com/quodlibet/quodlibet/pull/2313/commits/bebd0ef523fe1d6a5df2c6bf958c6cf7d1e8aaee for the code needed to mark quodlibet.optpackages as "not part of the project".

All in all I'm open to rework this in the future if an alternative arises.

**Comment by lazka** [comment]
> Thanks. I'll look into making it possible for more people to see the data.

I've asked if we can get another user.

**Comment by declension** [comment]
> I haven't checked, but zip import might work. Is there any problem with your IDE and the current solution?

Zip import sounds good. No problems as such, more just being in the source tree it gets treated like real source code, e.g. highlighting problems (>1000 warnings). I suppose we can just configure IDEs to also ignore that folder tree.

BTW do we need _any_ of `optpackages/raven/contrib` (support for Django / Celery / Tornado etc)?

> All in all I'm open to rework this in the future if an alternative arises.

OK so maybe let's get it in now and think of something to do with build steps / zip imports separately...

**Comment by lazka** [comment]
> BTW do we need any of optpackages/raven/contrib (support for Django / Celery / Tornado etc)?

Thanks. I've removed that now and automated the process: https://github.com/quodlibet/quodlibet/pull/2313/commits/0c026ea5e03156e85360ed6f60a7ce24ed97dd5f

(and sqashed/reorderd the patches..)

**Comment by lazka** [comment]
> > Thanks. I'll look into making it possible for more people to see the data.
>
> I've asked if we can get another user.

Our account got upgraded now.

**Pull request merged**
